version: "3"

networks:
    mysitedefault:
      ipam:
        config:
          - subnet: 172.200.0.0/24
services:
    php-fpmadmin:
        build: install/php-fpmadmin
        ports:
            - 9030:9000
        volumes:
            - ./code/admin:/var/www/html/
            - ./install/php-fpm/supervisor:/etc/supervisor/conf.d/
        links:
            - db
        networks:
            mysitedefault:
                ipv4_address: 172.200.0.3
    nginxadmin:
        build: install/nginxadmin
        ports:
            - 8090:80
        volumes:
            - ./code/admin:/var/www/html/
        links:
            - php-fpmadmin
        networks:
            mysitedefault:
                ipv4_address: 172.200.0.4
    db:
        image: mysql:5.7
        ports:
            - 3330:3306
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./install/mysql/init:/docker-entrypoint-initdb.d
        networks:
            mysitedefault:
                ipv4_address: 172.200.0.5
    cache:
        image: redis:3.0-alpine
        volumes:
          - ./data/redis:/data
        ports:
          - "6382:6379"
        networks:
            mysitedefault:
                ipv4_address: 172.200.0.6
